name: TypeScript Linting

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'fastlane/**'
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies with mise
        uses: jdx/mise-action@v3

      - name: Install dependencies
        run: pnpm install

      - name: Lint with expo
        run: pnpm expo lint --max-warnings 0

      - name: Run TypeScript checks
        run: pnpm tsc
